version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - openai_server

  openai_server:
    build: .
    container_name: openai_container
    ports:
      - 5000:5000
    env_file:
      - ./.env
