name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run Jest
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run test-cover
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Deploy to Google Compute Engine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd OpenAI-service
          git pull
          docker-compose up --build  -d
