name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Jest
      run: |
        npm ci
        npm run test-cover
    
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Deploy to Google Compute Engine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd OpenAI-service
          git pull
          docker-compose up --build  -d
